### ISSUE TITLE
Any way to consolidate master and multi_os branches?

### ISSUE THREAD

**Issue by smokhov** [gcielniak/OpenCL-Tutorials#12]
Otherwise, either one or the other falls behind and both require maintenance.
VS2019 and others work very well with cmake files and one can generate
VS solutions from cmake without issues... Is there still a need to maintain
dedicated .sln files when VS can work directly with cmakefile.txt or use
its -G generator functionality?

Thanks!

**Comment by gcielniak** [comment]
A fair point! This material, however, was designed for a specific course and students who were not familiar with the cmake workflow. Since the course is still running and I am not a course tutor anymore I would need to leave it as it is. Sorry!
